apiVersion: v1 ## To create a pod
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    demo: service
spec:
  # list of containers
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1 ## To create service bydefault is cluster ip
kind: Service
metadata:
  name: nginx-service
spec:
  selector:  ## based on the above labels the service will attach to the pod.
    app: nginx
    demo: service
  ports:
  - protocol: TCP
    port: 80 #service-port(cluster ip)
    targetPort: 80 #container-port

## if anybody hits the service port then it is farwards to container.


# To get the list of services 
# kubectl get services
# (or)
# kubectl get svc