apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: env-demo-container
    image: nginx
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"

## Env is hardcoded here to avoid that we can store the values in configmap. Map is nothing but stores key value pairs andwe stores files aslo.