---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-1
spec:
  # list of containers
  containers:
  - name: config-pod-1
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: config01 #Name of the config map in 07_config_maps file 4th line.

## we have given the configmap file name here so all the values inside that file will be taken dynamically.