apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce #EBS volume should have readwriteonce, because it is HD attached to a one server. EFS can be attached to many.
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0991aef58807fc1e2  ##Replace the volume ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set. for static provisioning this is empty
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-pod
  labels:
    demo: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:  ## The volume is created in AZ-1a and it should be attach to 1a worker nodes. We have to assign a lable to nodes.
    zone: 1a
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port





## Create an EBS volume 
## Install aws-ebs-csi drivers in eksctl workstation using below command to connect the volume
## kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.28"
## Assign IAM role with ec2 full access to the worker node to create, delete the voumes.

## kubectl get nodes
## kubectl get nodes --show-labels
## Based on the worker nodes AZ assign lables 
## kubectl label nodes <node_name> zone=1a
## kubectl apply -f 03_EBS-Static_provisioning.yaml
## kubectl exec -it ebs-static-pod -- bash
## echo "<h1>Hello this is from EBS Static</h1>" >> /usr/share/nginx/html/ebs.html
## Now copy the LB_dns/ebs.html and search in google

## Even if the pod is deleted and new pod created still access the same storage.